texts = {
    "ORDER_REGISTRATION": "ثبت سفارش",
    "MORE":               "بیشتر",
    "WELCOME":            "درود",
    "MORE_TEXT":          "منوی مد نظر خود را انتخاب کنید.",
    "ORDER_HISTORY": "سفارشات",
    "FINANCE":       "مالی",
    "HELP":          "راهنما",
    "ABOAT_US":      "درباره ما",
    "SUPORT":        "پشتیبانی",
    "ADMIN_PANEL_HEADER":  "پنل مدیریت",
    "ADMIN_ORDERS_BTN":    "سفارشات",
    "ADMIN_USERS_BTN":     "کاربران",
    "ADMIN_ITEMS_BTN":     "مدیریت آیتم‌ها",
    "ADMIN_MODELS_BTN":    "مدیریت مدل‌ها",
    "ADMIN_STATS_BTN":     "آمار",
    "ADMIN_EXIT_BTN":      "خروج از پنل",
    "ADMIN_USERS_HEADER":  "مدیریت کاربران",
    "BACK_BTN":           "🔙 بازگشت",
    "BACK_TO_PANEL_BTN":  "🔙 بازگشت به پنل",
    "BACK_TO_ORDERS_BTN": "🔙 بازگشت به سفارشات",
    "CANCEL_BTN":         "❌ لغو",
    "SKIP_BTN":           "رد کردن ⏭",
    "CONFIRM_DELETE_BTN": "✅ بله، حذف کن",
    "YES_NOW_BTN":        "✅ بله",
    "NO_LATER_BTN":       "❌ خیر",
    "COMING_SOON":        "به زودی...",
    "SAVE_MODEL":         "ذخیره مدل",
    "STATUS_PENDING":     "⏳ در انتظار",
    "STATUS_CONFIRMED":   "✅ تأیید شده",
    "STATUS_IN_PROGRESS": "🔄 در حال انجام",
    "STATUS_DELIVERED":   "📦 تحویل داده شده",
    "STATUS_CANCELLED":   "❌ لغو شده",
    "STATUS_ACTION_CONFIRM": "✅ تأیید",
    "STATUS_ACTION_CANCEL":  "❌ لغو",
    "STATUS_ACTION_START":   "🔄 شروع",
    "STATUS_ACTION_DELIVER": "📦 تحویل",
    "STATUS_CHANGED_OK":     "وضعیت به {status} تغییر یافت.",
    "PAY_STATUS_PENDING":  "⏳ در انتظار",
    "PAY_STATUS_APPROVED": "✅ تأیید شده",
    "PAY_STATUS_REJECTED": "❌ رد شده",
    "SIDE_LEFT":       "👈 چپ",
    "SIDE_RIGHT":      "👉 راست",
    "HAND_LEFT":       "*چپ*",
    "HAND_RIGHT":      "*راست*",
    "HAND_LEFT_PLAIN":  "چپ",
    "HAND_RIGHT_PLAIN": "راست",
    "SIDE_TYPE_NONE":        "بدون طرف",
    "SIDE_TYPE_BOTH":        "دو طرف",
    "SIDE_TYPE_SINGLE":      "یک طرف",
    "SIDE_TYPE_SINGLE_LONG": "یک طرف (مشخص می‌شود)",
    "SELECT_MODEL_PROMPT":         "لطفاً مدل مورد نظر را انتخاب کنید:",
    "SELECT_ITEMS_PROMPT":         "مدل: *{model_name}*\nآیتم‌های مورد نظر را انتخاب کنید:",
    "MODEL_BTN":                   "📦 {model_name}  ({item_count} آیتم)",
    "MODEL_NO_ITEMS":              "این مدل آیتمی ندارد.",
    "ASK_QTY":                     "تعداد *{item_name}* را وارد کنید:",
    "ASK_SIDE":                    "طرف دسته *{item_name}* را انتخاب کنید:",
    "ASK_INVOICE":                 "شماره فاکتور را وارد کنید (یا رد کنید):",
    "ASK_CUSTOMER":                "نام مشتری را وارد کنید (یا رد کنید):",
    "ASK_DELIVERY":                "تاریخ تحویل را وارد کنید (مثال: ۱۴۰۳/۰۶/۱۵):",
    "ASK_FABRIC":                  "نام پارچه را وارد کنید:",
    "ASK_NOTES":                   "توضیحات را وارد کنید (یا رد کنید):",
    "CONFIRM_SELECTION_BTN":       "✅ تأیید انتخاب ({count})",
    "CONFIRM_SELECTION_BTN_EMPTY": "انتخابی وجود ندارد",
    "ITEM_SELECTED":               "✅ آیتم اضافه شد",
    "ITEM_REMOVED":                "❌ آیتم حذف شد",
    "ORDER_REG_CANCELLED":         "❌ ثبت سفارش لغو شد.",
    "CONFIRM_HEADER":       "📋 *خلاصه سفارش*",
    "CONFIRM_MODEL":        "مدل: *{model_name}*",
    "CONFIRM_ITEMS_HEADER": "\n*آیتم‌ها:*",
    "CONFIRM_SIDE_SINGLE":  " | طرف: {hand}",
    "CONFIRM_SIDE_BOTH":    " | دو طرف",
    "CONFIRM_PRICE":        " | {price:,} تومان",
    "CONFIRM_SUBTOTAL":     "  جمع: {subtotal:,} تومان",
    "CONFIRM_TOTAL":        "\n💰 *جمع کل: {total:,} تومان*",
    "CONFIRM_INVOICE":      "فاکتور: {val}",
    "CONFIRM_CUSTOMER":     "مشتری: {val}",
    "CONFIRM_DELIVERY":     "تاریخ تحویل: {val}",
    "CONFIRM_FABRIC":       "پارچه: {val}",
    "CONFIRM_NOTES":        "توضیحات: {val}",
    "CONFIRM_YES_BTN":      "✅ تأیید و ثبت",
    "CONFIRM_NO_BTN":       "❌ لغو",
    "ORDER_SAVED":      "✅ سفارش شما با شماره *#{order_id}* ثبت شد.",
    "ADMIN_NEW_ORDER":  (
        "🔔 *سفارش جدید #{order_id}*\n"
        "chat\\_id: `{cid}`\n"
        "مدل: {model_name}\n"
        "مشتری: {customer_name}\n"
        "پارچه: {fabric_name}\n"
        "تحویل: {delivery_date}\n"
        "💰 جمع کل: {total_price:,} تومان"
    ),
    "ORDER_STATUS_CHANGED": "📣 وضعیت سفارش *#{order_id}* به *{status}* تغییر یافت.",
    "ORDER_DETAIL_HEADER":       "📋 *جزئیات سفارش #{order_id}*",
    "ORDER_DETAIL_STATUS":       "وضعیت: {status}",
    "ORDER_DETAIL_FABRIC":       "پارچه: {val}",
    "ORDER_DETAIL_CUSTOMER":     "مشتری: {val}",
    "ORDER_DETAIL_DELIVERY":     "تاریخ تحویل: {val}",
    "ORDER_DETAIL_DATE":         "تاریخ ثبت: {val}",
    "ORDER_DETAIL_INVOICE":      "شماره فاکتور: {val}",
    "ORDER_DETAIL_NOTES":        "توضیحات: {val}",
    "ORDER_DETAIL_ITEMS_HEADER": "\n*آیتم‌ها:*",
    "ORDER_DETAIL_SIDE":         " | طرف: {hand}",
    "ORDER_DETAIL_TOTAL":        "\n💰 *جمع کل: {total:,} تومان*",
    "NO_ITEMS_REGISTERED":       "آیتمی ثبت نشده است.",
    "ADMIN_ORDER_DETAIL_HEADER":   "📋 *جزئیات سفارش #{order_id}*",
    "ADMIN_ORDER_DETAIL_DATE":     "تاریخ ثبت: {val}",
    "ADMIN_ORDER_DETAIL_FABRIC":   "پارچه: {val}",
    "ADMIN_ORDER_DETAIL_CUSTOMER": "مشتری: {val}",
    "ADMIN_ORDER_DETAIL_DELIVERY": "تاریخ تحویل: {val}",
    "ADMIN_ORDER_DETAIL_USER":     "کاربر: {name} | {phone}",
    "ORDER_FILES_COUNT":           "📎 فایل‌های پیوست: {count} عدد",
    "ORDER_NOT_FOUND":             "سفارش یافت نشد.",
    "NO_ORDERS":            "هیچ سفارشی ثبت نشده است.",
    "NO_ORDERS_STATUS":     "هیچ سفارشی با وضعیت {status} وجود ندارد.",
    "ORDERS_SUMMARY_HEADER":"📦 *خلاصه سفارشات شما:*",
    "ORDERS_LIST_HEADER":   "📋 *سفارشات {status}* ({count} عدد):",
    "ORDERS_FILTER_HEADER": "📋 *سفارشات {status}:*",
    "NEW_ORDER_BTN":        "➕ سفارش جدید",
    "CANCEL_ORDER_BTN":     "❌ لغو سفارش",
    "NO_CANCELLABLE_ORDERS":"هیچ سفارش قابل لغوی وجود ندارد.",
    "CANCEL_ORDER_PROMPT":  "کدام سفارش را می‌خواهید لغو کنید؟",
    "CANCEL_ORDER_BTN_ITEM":"❌ سفارش #{order_id} — {date}",
    "ORDER_CANCELLED_OK":   "✅ سفارش #{order_id} لغو شد.",
    "ORDER_CANCEL_FAIL":    "❌ امکان لغو این سفارش وجود ندارد.",
    "FINANCE_SUMMARY":         "💰 *خلاصه مالی*\nکل: {total:,} تومان\nپرداخت شده: {paid:,} تومان\nمانده: {remaining:,} تومان",
    "FINANCE_NEW_PAYMENT":     "💳 پرداخت جدید",
    "FINANCE_PAYMENT_HISTORY": "📜 تاریخچه پرداخت‌ها",
    "FINANCE_DEBTS":           "📋 بدهی‌ها",
    "NO_DEBTS":                "هیچ بدهی‌ای ثبت نشده است.",
    "DEBTS_LIST_HEADER":       "📋 *بدهی‌های شما:*",
    "NO_PAYMENTS":             "هیچ پرداختی ثبت نشده است.",
    "PAYMENTS_HISTORY_HEADER": "📜 *تاریخچه پرداخت‌ها:*",
    "MODELS_MANAGE_HEADER":            "📦 *مدیریت مدل‌ها:*",
    "MODELS_MANAGE_EMPTY":             "هیچ مدلی تعریف نشده است.",
    "ADD_MODEL_BTN":                   "➕ افزودن مدل",
    "ASK_NEW_MODEL_NAME":              "نام جدید مدل را وارد کنید:",
    "ASK_NEW_MODEL_NAME_INPUT":        "نام مدل جدید را وارد کنید:",
    "ASK_ADD_ITEMS_NOW":               "مدل *{model_name}* ساخته شد. آیا الان آیتم اضافه می‌کنید؟",
    "ASK_MODEL_ITEM_COUNT":            "مدل: *{model_name}*\nچند آیتم دارد؟",
    "MODEL_SAVED_NO_ITEMS":            "✅ مدل *{model_name}* ذخیره شد (بدون آیتم).",
    "MODEL_SAVED_WITH_ITEMS":          "✅ مدل *{model_name}* با {item_count} آیتم ذخیره شد.",
    "MODEL_NAME_CHANGED":              "✅ نام مدل به *{new_name}* تغییر یافت.",
    "MODEL_DELETED_OK":                "✅ مدل حذف شد.",
    "CONFIRM_MODEL_DELETE_WITH_ITEMS": "⚠️ این مدل دارای {item_count} آیتم است. آیا مطمئن هستید؟",
    "CONFIRM_MODEL_DELETE_EMPTY":      "آیا از حذف این مدل مطمئن هستید؟",
    "CONFIRM_MODEL_DELETE_BTN":        "✅ حذف ({item_count} آیتم)",
    "NO_MODELS_DEFINED":               "هیچ مدلی تعریف نشده است.",
    "ADMIN_ITEMS_HEADER":        "📋 *آیتم‌های مدل {model_name}:*\n",
    "ADMIN_ITEMS_MANAGE_HEADER": "📦 *مدل‌ها:*",
    "ADMIN_ITEMS_MANAGE_EMPTY":  "هیچ مدلی وجود ندارد.",
    "NO_ITEMS":                  "آیتمی برای این مدل تعریف نشده است.",
    "ADD_ITEM_BTN":              "➕ افزودن آیتم",
    "ASK_NEW_ITEM_NAME":         "نام آیتم جدید را وارد کنید:",
    "ASK_ITEM_NAME_FIRST":       "نام آیتم اول را وارد کنید:",
    "ASK_ITEM_NAME_N":           "نام آیتم {n} را وارد کنید:",
    "ASK_ITEM_PRICE":            "قیمت *{item_name}* را وارد کنید (تومان، عدد):",
    "ASK_ITEM_SIDE_TYPE":        "نوع طرف *{item_name}* را انتخاب کنید:",
    "ASK_ITEM_SIDE_TYPE_SHORT":  "نوع طرف را انتخاب کنید:",
    "ITEM_EDIT_HEADER":          "✏️ *ویرایش آیتم: {item_name}*\nقیمت: {price}\nطرف: {side}",
    "ITEM_ADDED_OK":             "✅ آیتم اضافه شد.",
    "ITEM_DELETED_OK":           "✅ آیتم حذف شد.",
    "CONFIRM_ITEM_DELETE":       "⚠️ آیا از حذف *{item_name}* مطمئن هستید؟",
    "SIDE_UPDATED_OK":           "✅ طرف آیتم به‌روز شد.",
    "EDIT_NAME_BTN":             "✏️ نام",
    "EDIT_PRICE_BTN":            "💰 قیمت",
    "EDIT_SIDE_BTN":             "↔️ طرف",
    "ASK_NEW_NAME":              "نام جدید را وارد کنید:",
    "ASK_NEW_PRICE":             "قیمت جدید را وارد کنید (تومان، عدد):",
    "EDIT_DONE":                 "✅ ویرایش انجام شد.",
    "NO_USERS":           "هیچ کاربری ثبت نشده است.",
    "USERS_LIST_HEADER":  "👥 *کاربران* ({count} نفر):",
    "USERS_LIST_BTN":     "👥 لیست کاربران",
    "ADD_USER_BTN":       "➕ افزودن کاربر",
    "ASK_USER_NAME":      "نام کاربر را وارد کنید:",
    "ASK_USER_PHONE":     "شماره تلفن کاربر را وارد کنید:",
    "ASK_USER_CHATID":    "chat_id کاربر را وارد کنید:",
    "USER_ADDED_OK":      "✅ کاربر *{name}* اضافه شد.",
    "USER_UPDATED_OK":    "✅ اطلاعات کاربر به‌روز شد.",
    "USER_DELETED_OK":    "✅ کاربر حذف شد.",
    "CONFIRM_USER_DELETE":"⚠️ آیا از حذف این کاربر مطمئن هستید؟",
    "EDIT_PHONE_BTN":     "📞 تلفن",
    "EDIT_ACCESS_BTN":    "🔑 سطح دسترسی",
    "LABEL_NAME":         "نام",
    "LABEL_PHONE":        "تلفن",
    "ASK_NEW_FIELD":      "{label} جدید را وارد کنید:",
    "SUPERUSER_STATUS":   "سوپریوزر",
    "NORMAL_USER_STATUS": "کاربر عادی",
    "ACCESS_CHANGED":     "✅ سطح دسترسی به {status} تغییر یافت.",
    "OPERATION_CANCELLED":  "❌ عملیات لغو شد.",
    "NO_ACTIVE_OPERATION":  "هیچ عملیات فعالی وجود ندارد.",
    "ERR_USER_NOT_FOUND":    "❌ کاربر یافت نشد.",
    "ERR_ORDER_SAVE":        "❌ خطا در ثبت سفارش: {e}",
    "ERR_QTY_INVALID":       "❌ لطفاً یک عدد صحیح مثبت وارد کنید.",
    "ERR_DATE_FORMAT":       "❌ فرمت تاریخ اشتباه است. لطفاً به صورت `۱۴۰۳/۰۶/۱۵` وارد کنید.",
    "ERR_FABRIC_EMPTY":      "❌ نام پارچه نمی‌تواند خالی باشد.",
    "ERR_SELECT_MIN_ONE":    "❌ حداقل یک آیتم انتخاب کنید.",
    "ERR_PRICE_NOT_NUMBER":  "❌ قیمت باید عدد باشد.",
    "ERR_NUMBER_INVALID":    "❌ لطفاً یک عدد معتبر وارد کنید.",
    "ERR_NAME_EMPTY":        "❌ نام نمی‌تواند خالی باشد.",
    "ERR_CHATID_NOT_NUMBER": "❌ chat_id باید عدد باشد.",
    "ERR_USER_SAVE":         "❌ خطا در ذخیره کاربر: {e}",
    "ERR_DIGITS_ONLY":       "❌ لطفاً فقط عدد وارد کنید.",
    "ERR_GENERIC":           "❌ خطایی رخ داد.",
    "ERR_DELETE":            "❌ خطا در حذف: {e}",
    "ERR_MODEL_DELETE":      "❌ خطا در حذف مدل.",
    "ERR_DB":                "❌ خطای پایگاه داده: {e}",
    "suport_message":  "برای گزارش هرگونه مشکل در روند ربات به ایدی زیر مراجعه کنید\n@Ardalanch",
    "aboatus_message": "این متن درباره ما است",
    "help_message":    "این متن راهنما است",
    "STATS_COMING_SOON": "📊 *بخش آمار*\n\nاین بخش هنوز تکمیل نشده و به زودی در دسترس قرار می‌گیرد.",
    "STATS_BACK_BTN":    "🔙 بازگشت به پنل",
}
